#pragma once

#define VIN_R1 10000.0f
#define VIN_R2 1000.0f
#define R_SHUNT 0.003f
#define CURRENT_SENSE_GAIN 100.0f

#define BATT_DESIGNED_CAPACITY 2.0f

#define CHARGE_CURRENT_CUTOFF 1.5f
#define CHARGE_VOLTAGE_CUTOFF 30.0f
#define CHARGE_VOLTAGE_MIN 28.8f

#define BATT_ABSOLUTE_MAX 28.7f
#define BATT_ABSOLUTE_MIN 21.7f

#define BATT_FULL (BATT_ABSOLUTE_MAX - 0.3f)
#define BATT_EMPTY (BATT_ABSOLUTE_MIN + 0.3f)
