name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install environment
        uses: .github/actions/platformio-env
      - name: Build
        shell: bash
        run: |
          export PATH=$PATH:~/.platformio/penv/bin
          pio run -v