name: Build and Push micro-ROS image

on:
  push:
    branches: [ main ]
    paths:
      - '.github/micro-ros/Dockerfile'
      - '.github/workflows/micro-ros-image.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/micro-ros/Dockerfile'
      - '.github/workflows/micro-ros-image.yaml'
  workflow_dispatch:  # Allows manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .github/micro-ros/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:micro-ros
          cache-from: type=gha
          cache-to: type=gha,mode=max